const A='/assets/';
const app=document.querySelector('#app');
const db=window.EA_SUPABASE;
const nav=[['home','⌂','Beranda'],['planning','☷','Planning'],['goals','◎','Goals'],['journal','✎','Journal'],['ideas','✦','Ideas'],['projects','□','Projects'],['journey','↗','Journey'],['profile','◉','Profile']];
const focusOptions=['Karya','Bisnis','Karier','Pendidikan','Kehidupan','Kreativitas'];
let state={session:null,user:null,profile:null,selected:[],onStep:1,active:'home',loading:false,cache:{goals:[],tasks:[],journal:[],ideas:[],projects:[]}};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const msg=(text,type='error')=>`<div class="notice ${type}">${esc(text)}</div>`;
async function loadSession(){const {data,error}=await db.auth.getSession();if(error)throw error;state.session=data.session;state.user=data.session?.user||null;if(state.user){const {data:p}=await db.from('profiles').select('*').eq('id',state.user.id).maybeSingle();state.profile=p||{id:state.user.id,name:state.user.user_metadata?.name||'Kreator',username:state.user.user_metadata?.username||'',email:state.user.email};state.selected=state.profile.focus||[]}}
function splash(){app.innerHTML=`<div class="splash"><img class="bg" src="${A}splash.jpg"><div class="content"><img class="logo" src="${A}logoea.png"><div class="word">EA PLAN</div><div class="tag">YOUR PERSONALIZED PLANNING JOURNEY</div></div></div>`;setTimeout(()=>{document.querySelector('.splash')?.classList.add('hide');setTimeout(()=>state.session?dashboard():welcome(),650)},3000)}
function welcome(){app.innerHTML=`<div class="authShell"><div class="authVisual"><img src="${A}splash.jpg"><div class="visualText"><div class="ey">PLAN · CREATE · REFLECT · GROW</div><h1>Rancang hidupmu.<br>Rawat perjalananmu.</h1><p>Ruang untuk merencanakan langkah, menyimpan ide, menulis cerita, mengelola proyek, dan melihat pertumbuhan dari waktu ke waktu.</p></div></div><div class="authPanel"><div class="authBox"><img class="miniLogo" src="${A}logoea.png"><div class="brandText">EA PLAN</div><h2>Mulai perjalananmu.</h2><p class="sub">Satu langkah kecil hari ini dapat menjadi bagian dari karya besar esok hari.</p><div class="form"><button class="goldBtn" onclick="register()">Buat Akun</button><button class="ghostBtn" onclick="login()">Sudah punya akun? Masuk</button></div><p class="switch">Ruang privatmu tersimpan aman di akun EA PLAN.</p></div></div></div>`}
function auth(mode,notice=''){const reg=mode==='register';app.innerHTML=`<div class="authPanel authFull"><div class="authBox"><img class="miniLogo" src="${A}logoea.png"><div class="brandText">EA PLAN</div><h2>${reg?'Buat akun.':'Selamat datang kembali.'}</h2><p class="sub">${reg?'Buat ruang perjalanan pribadimu.':'Masuk untuk melanjutkan perjalananmu.'}</p>${notice?msg(notice,'info'):''}<form class="form" onsubmit="submitAuth(event,'${mode}')">${reg?'<input class="input" id="name" placeholder="Nama" required><input class="input" id="username" placeholder="Username" required>':''}<input class="input" id="email" type="email" placeholder="Email" autocomplete="email" required><input class="input" id="password" type="password" placeholder="Password" minlength="6" autocomplete="current-password" required><div id="err"></div><button class="goldBtn" type="submit">${reg?'Buat Akun':'Masuk'}</button></form><div class="switch"><button class="link" onclick="welcome()">← Kembali</button> · <button class="link" onclick="forgot()">Lupa password?</button></div></div></div>`}
function register(){auth('register')}function login(){auth('login')}
async function submitAuth(e,mode){e.preventDefault();const er=document.querySelector('#err');er.innerHTML='';const email=document.querySelector('#email').value.trim().toLowerCase(),password=document.querySelector('#password').value;if(mode==='register'){const name=document.querySelector('#name').value.trim(),username=document.querySelector('#username').value.trim();const {data,error}=await db.auth.signUp({email,password,options:{data:{name,username}}});if(error){er.innerHTML=msg(error.message);return}if(!data.session){auth('login','Akun berhasil dibuat. Periksa emailmu untuk verifikasi, lalu masuk.');return}await loadSession();onboarding()}else{const {data,error}=await db.auth.signInWithPassword({email,password});if(error){er.innerHTML=msg(error.message);return}state.session=data.session;state.user=data.user;await loadSession();if(state.profile?.onboarding_completed)dashboard();else onboarding()}}
function forgot(){app.innerHTML=`<div class="authPanel authFull"><div class="authBox"><div class="brandText">EA PLAN</div><h2>Reset password.</h2><p class="sub">Masukkan email untuk menerima instruksi pemulihan.</p><form class="form" onsubmit="sendReset(event)"><input class="input" id="resetEmail" type="email" placeholder="Email" required><div id="resetErr"></div><button class="goldBtn">Kirim instruksi</button></form><div class="switch"><button class="link" onclick="login()">← Kembali ke login</button></div></div></div>`}
async function sendReset(e){e.preventDefault();const el=document.querySelector('#resetErr');const email=document.querySelector('#resetEmail').value.trim().toLowerCase();const {error}=await db.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin});el.innerHTML=error?msg(error.message):msg('Instruksi reset telah dikirim jika email tersebut terdaftar.','success')}
function onboarding(){state.onStep=1;renderOnboarding()}
function renderOnboarding(){const body=state.onStep===1?`<div class="kicker">LANGKAH 1</div><h2>Apa yang ingin kamu kembangkan?</h2><p class="sub">Pilih yang paling dekat dengan perjalananmu. Kamu bisa memilih lebih dari satu.</p><div class="choices">${focusOptions.map(x=>`<button class="choice ${state.selected.includes(x)?'selected':''}" onclick="pick('${x}')">${state.selected.includes(x)?'✓':'○'} ${x}</button>`).join('')}</div>`:state.onStep===2?`<div class="kicker">LANGKAH 2</div><h2>Ceritakan sedikit tentangmu.</h2><p class="sub">Bagian ini opsional. Profil dapat kamu ubah nanti.</p><textarea class="input" id="bio" rows="6" placeholder="Apa yang sedang kamu perjuangkan atau bangun?">${esc(state.profile?.bio||'')}</textarea>`:`<div class="kicker">LANGKAH 3</div><h2>Apa target utamamu?</h2><p class="sub">Kita mulai dari satu target yang benar-benar berarti.</p><input class="input" id="firstGoal" placeholder="Contoh: menyelesaikan karya pertama saya">`;app.innerHTML=`<div class="onboard"><div class="onboardBox"><div class="brandText">EA PLAN</div><div class="steps"><i class="${state.onStep>=1?'active':''}"></i><i class="${state.onStep>=2?'active':''}"></i><i class="${state.onStep>=3?'active':''}"></i></div>${body}<div class="actions">${state.onStep>1?'<button class="ghostBtn" onclick="state.onStep--;renderOnboarding()">Kembali</button>':''}<button class="goldBtn" onclick="nextOnboard()">${state.onStep<3?'Lanjut':'Masuk ke EA PLAN'}</button></div></div></div>`}
function pick(x){state.selected=state.selected.includes(x)?state.selected.filter(y=>y!==x):[...state.selected,x];renderOnboarding()}
async function nextOnboard(){if(state.onStep===1&&!state.selected.length){alert('Pilih minimal satu fokus.');return}if(state.onStep<3){if(state.onStep===2&&document.querySelector('#bio'))state.profile={...(state.profile||{}),bio:document.querySelector('#bio').value};state.onStep++;renderOnboarding();return}const bio=document.querySelector('#bio')?.value??state.profile?.bio??'';const firstGoal=document.querySelector('#firstGoal')?.value.trim();const p={id:state.user.id,name:state.profile?.name||state.user.user_metadata?.name,username:state.profile?.username||state.user.user_metadata?.username,email:state.user.email,bio,focus:state.selected,onboarding_completed:true,updated_at:new Date().toISOString()};const {error}=await db.from('profiles').upsert(p);if(error){alert(error.message);return}state.profile={...state.profile,...p};if(firstGoal){const {error:e}=await db.from('goals').insert({user_id:state.user.id,title:firstGoal,progress:0,status:'active'});if(e)alert(e.message)}dashboard()}
async function loadData(){if(!state.user)return;const uid=state.user.id;const [g,t,j,i,p]=await Promise.all([db.from('goals').select('*').eq('user_id',uid).order('created_at',{ascending:false}),db.from('tasks').select('*').eq('user_id',uid).order('created_at',{ascending:false}),db.from('journal_entries').select('*').eq('user_id',uid).order('created_at',{ascending:false}),db.from('ideas').select('*').eq('user_id',uid).order('created_at',{ascending:false}),db.from('projects').select('*').eq('user_id',uid).order('created_at',{ascending:false})]);state.cache={goals:g.data||[],tasks:t.data||[],journal:j.data||[],ideas:i.data||[],projects:p.data||[]}}
async function dashboard(){await loadData();state.active='home';renderApp()}
function renderApp(){const n=nav.find(x=>x[0]===state.active)||nav[0];let content=state.active==='home'?home():state.active==='planning'?planning():state.active==='goals'?goals():state.active==='journal'?journal():state.active==='ideas'?ideas():state.active==='projects'?projects():state.active==='journey'?journey():profile();app.innerHTML=`<div class="appShell"><aside class="side"><div class="sideBrand"><img src="${A}logoea.png"><span>EA PLAN</span></div><nav class="nav">${nav.map(x=>`<button class="${x[0]===state.active?'active':''}" onclick="go('${x[0]}')">${x[1]}&nbsp;&nbsp;${x[2]}</button>`).join('')}<button onclick="logout()">↪&nbsp;&nbsp;Keluar</button></nav></aside><main class="main"><header class="top"><div><div class="kicker">RUANG PERJALANAN</div><h2>${n[2]}</h2></div><div class="avatar">${esc((state.profile?.name||'EA').slice(0,2).toUpperCase())}</div></header>${content}</main><nav class="mobileNav">${[['home','⌂','Beranda'],['planning','☷','Plan'],['goals','◎','Goals'],['journey','↗','Journey'],['profile','◉','Profil']].map(x=>`<button class="${x[0]===state.active?'active':''}" onclick="go('${x[0]}')"><b>${x[1]}</b>${x[2]}</button>`).join('')}</nav></div>`}
function home(){const c=state.cache,g=c.goals.length,done=c.goals.filter(x=>x.status==='completed').length,progress=g?Math.round(c.goals.reduce((s,x)=>s+x.progress,0)/g):0;return `<div class="grid"><article class="card wide"><div class="kicker">SELAMAT DATANG, ${esc((state.profile?.name||'KREATOR').toUpperCase())}</div><h1 class="heroTitle">Rancang hidupmu.<br>Rawat perjalananmu.</h1><p class="muted">“Setiap karya besar berawal dari satu langkah kecil yang terencana.”</p></article><article class="card"><div class="kicker">PROGRESS</div><div class="metric">${progress}%</div><div class="progress"><i style="width:${progress}%"></i></div><span class="muted">${done} dari ${g} target selesai.</span></article><article class="card"><div class="kicker">TARGET AKTIF</div><div class="metric">${c.goals.filter(x=>x.status==='active').length}</div><span class="muted">Target yang sedang kamu jalankan.</span></article><article class="card"><div class="kicker">PROJECTS</div><div class="metric">${c.projects.length}</div><span class="muted">Ruang karya yang sedang tumbuh.</span></article><article class="card"><div class="kicker">JOURNAL</div><div class="metric">${c.journal.length}</div><span class="muted">Catatan perjalananmu.</span></article><article class="card full"><h3>Langkah hari ini</h3>${c.tasks.filter(x=>!x.completed).slice(0,3).map(t=>`<div class="item taskRow"><span>○ ${esc(t.title)}</span><button class="smallBtn" onclick="completeTask('${t.id}')">Selesai</button></div>`).join('')||'<div class="item">Belum ada task. Tambahkan satu prioritas di Planning.</div>'}</article></div>`}
function planning(){return `<div class="grid"><article class="card full"><div class="kicker">PLANNING</div><h1 class="pageTitle">Susun langkah dengan sederhana.</h1><form class="inlineForm" onsubmit="addTask(event)"><input class="input lightInput" id="taskTitle" placeholder="Tambahkan prioritas..." required><input class="input lightInput" id="taskDate" type="date"><button class="goldBtn">Tambah</button></form>${state.cache.tasks.map(t=>`<div class="item taskRow"><span class="${t.completed?'strike':''}">${t.completed?'✓':'○'} ${esc(t.title)} ${t.due_date?`<small>${esc(t.due_date)}</small>`:''}</span><div><button class="smallBtn" onclick="completeTask('${t.id}')">${t.completed?'Batal':'Selesai'}</button><button class="smallBtn danger" onclick="removeItem('tasks','${t.id}')">Hapus</button></div></div>`).join('')||'<p class="muted">Belum ada planning.</p>'}</article></div>`}
function goals(){return `<div class="grid"><article class="card full"><div class="kicker">GOALS</div><h1 class="pageTitle">Ubah mimpi menjadi target.</h1><form class="form lightForm" onsubmit="addGoal(event)"><input class="input lightInput" id="goalTitle" placeholder="Judul target" required><input class="input lightInput" id="goalDate" type="date"><textarea class="input lightInput" id="goalDesc" rows="3" placeholder="Deskripsi singkat"></textarea><button class="goldBtn">Tambah target</button></form>${state.cache.goals.map(g=>`<div class="item"><div class="itemHead"><strong>${esc(g.title)}</strong><span>${g.progress}%</span></div><div class="progress"><i style="width:${g.progress}%"></i></div><div class="rowActions"><input type="range" min="0" max="100" value="${g.progress}" oninput="updateGoalProgress('${g.id}',this.value)"><button class="smallBtn" onclick="toggleGoal('${g.id}', '${g.status}')">${g.status==='completed'?'Aktifkan':'Selesai'}</button><button class="smallBtn danger" onclick="removeItem('goals','${g.id}')">Hapus</button></div></div>`).join('')||'<p class="muted">Belum ada target.</p>'}</article></div>`}
function journal(){return moduleCRUD('journal','JOURNAL','Tulis apa yang terjadi, dirasakan, dan dipelajari.','Judul catatan','Tulis ceritamu...')}
function ideas(){return moduleCRUD('ideas','IDEAS','Tangkap ide sebelum hilang.','Judul ide','Catatan ide...')}
function moduleCRUD(type,kickerText,desc,titlePh,bodyPh){const arr=state.cache[type];return `<div class="grid"><article class="card full"><div class="kicker">${kickerText}</div><h1 class="pageTitle">${esc(desc)}</h1><form class="form lightForm" onsubmit="addTextItem(event,'${type}')"><input class="input lightInput" id="itemTitle" placeholder="${esc(titlePh)}" required><textarea class="input lightInput" id="itemBody" rows="4" placeholder="${esc(bodyPh)}"></textarea><button class="goldBtn">Simpan</button></form>${arr.map(x=>`<div class="item"><strong>${esc(x.title||'Tanpa judul')}</strong><p class="muted">${esc(x.body||'')}</p><button class="smallBtn danger" onclick="removeItem('${type}','${x.id}')">Hapus</button></div>`).join('')||'<p class="muted">Belum ada catatan.</p>'}</article></div>`}
function projects(){return `<div class="grid"><article class="card full"><div class="kicker">PROJECTS</div><h1 class="pageTitle">Pecah karya besar menjadi tahapan kecil.</h1><form class="form lightForm" onsubmit="addProject(event)"><input class="input lightInput" id="projectTitle" placeholder="Nama project" required><textarea class="input lightInput" id="projectDesc" rows="3" placeholder="Deskripsi"></textarea><button class="goldBtn">Buat project</button></form>${state.cache.projects.map(p=>`<div class="item"><div class="itemHead"><strong>${esc(p.title)}</strong><span>${p.progress}%</span></div><p class="muted">${esc(p.description||'')}</p><div class="progress"><i style="width:${p.progress}%"></i></div><div class="rowActions"><input type="range" min="0" max="100" value="${p.progress}" oninput="updateProjectProgress('${p.id}',this.value)"><button class="smallBtn danger" onclick="removeItem('projects','${p.id}')">Hapus</button></div></div>`).join('')||'<p class="muted">Belum ada project.</p>'}</article></div>`}
function journey(){const c=state.cache,g=c.goals.length,avg=g?Math.round(c.goals.reduce((s,x)=>s+x.progress,0)/g):0;return `<div class="grid"><article class="card wide"><div class="kicker">JOURNEY</div><h1 class="pageTitle">Pertumbuhanmu, dari waktu ke waktu.</h1><p class="muted">Progress rata-rata target saat ini.</p><div class="metric">${avg}%</div><div class="progress"><i style="width:${avg}%"></i></div></article><article class="card"><div class="kicker">CATATAN</div><div class="metric">${c.journal.length}</div><span class="muted">Refleksi yang tersimpan.</span></article><article class="card full"><h3>Target perjalanan</h3>${c.goals.map(x=>`<div class="item"><div class="itemHead"><span>${esc(x.title)}</span><strong>${x.progress}%</strong></div></div>`).join('')||'<div class="item">Mulai dengan membuat target pertama.</div>'}</article></div>`}
function profile(){return `<div class="grid"><article class="card full"><div class="kicker">PROFILE</div><h1 class="pageTitle">Ruang pribadimu.</h1><form class="form lightForm" onsubmit="saveProfile(event)"><label class="label lightLabel">Nama</label><input class="input lightInput" id="pName" value="${esc(state.profile?.name||'')}" required><label class="label lightLabel">Username</label><input class="input lightInput" id="pUsername" value="${esc(state.profile?.username||'')}" required><label class="label lightLabel">Bio</label><textarea class="input lightInput" id="pBio" rows="5">${esc(state.profile?.bio||'')}</textarea><button class="goldBtn">Simpan profil</button></form><button class="ghostBtn darkGhost" onclick="logout()">Keluar dari EA PLAN</button></article></div>`}
async function addTask(e){e.preventDefault();const title=document.querySelector('#taskTitle').value.trim(),due=document.querySelector('#taskDate').value||null;const {error}=await db.from('tasks').insert({user_id:state.user.id,title,due_date:due});if(error)return alert(error.message);await dashboard();go('planning')}
async function completeTask(id){const t=state.cache.tasks.find(x=>x.id===id);if(!t)return;const {error}=await db.from('tasks').update({completed:!t.completed,updated_at:new Date().toISOString()}).eq('id',id).eq('user_id',state.user.id);if(error)alert(error.message);else{await loadData();renderApp()}}
async function addGoal(e){e.preventDefault();const title=document.querySelector('#goalTitle').value.trim(),due=document.querySelector('#goalDate').value||null,description=document.querySelector('#goalDesc').value.trim();const {error}=await db.from('goals').insert({user_id:state.user.id,title,due_date:due,description});if(error)return alert(error.message);await dashboard();go('goals')}
async function updateGoalProgress(id,value){const {error}=await db.from('goals').update({progress:Number(value),status:Number(value)>=100?'completed':'active',updated_at:new Date().toISOString()}).eq('id',id).eq('user_id',state.user.id);if(error)alert(error.message);else{const g=state.cache.goals.find(x=>x.id===id);if(g){g.progress=Number(value);g.status=Number(value)>=100?'completed':'active';}}}
async function toggleGoal(id,status){const {error}=await db.from('goals').update({status:status==='completed'?'active':'completed',progress:status==='completed'?0:100,updated_at:new Date().toISOString()}).eq('id',id).eq('user_id',state.user.id);if(error)alert(error.message);else{await loadData();renderApp()}}
async function addTextItem(e,type){e.preventDefault();const title=document.querySelector('#itemTitle').value.trim(),body=document.querySelector('#itemBody').value.trim();const table=type==='journal'?'journal_entries':'ideas';const {error}=await db.from(table).insert({user_id:state.user.id,title,body});if(error)return alert(error.message);await dashboard();go(type)}
async function addProject(e){e.preventDefault();const title=document.querySelector('#projectTitle').value.trim(),description=document.querySelector('#projectDesc').value.trim();const {error}=await db.from('projects').insert({user_id:state.user.id,title,description});if(error)return alert(error.message);await dashboard();go('projects')}
async function updateProjectProgress(id,value){const {error}=await db.from('projects').update({progress:Number(value),status:Number(value)>=100?'completed':'active',updated_at:new Date().toISOString()}).eq('id',id).eq('user_id',state.user.id);if(error)alert(error.message);else{const p=state.cache.projects.find(x=>x.id===id);if(p){p.progress=Number(value);p.status=Number(value)>=100?'completed':'active';}}}
async function removeItem(type,id){if(!confirm('Hapus item ini?'))return;const table=type==='journal'?'journal_entries':type==='ideas'?'ideas':type;const {error}=await db.from(table).delete().eq('id',id).eq('user_id',state.user.id);if(error)alert(error.message);else{await dashboard();go(state.active)}}
async function saveProfile(e){e.preventDefault();const payload={name:document.querySelector('#pName').value.trim(),username:document.querySelector('#pUsername').value.trim(),bio:document.querySelector('#pBio').value.trim(),updated_at:new Date().toISOString()};const {error}=await db.from('profiles').update(payload).eq('id',state.user.id);if(error)alert(error.message);else{state.profile={...state.profile,...payload};alert('Profil tersimpan.');renderApp()}}
async function logout(){await db.auth.signOut();state={session:null,user:null,profile:null,selected:[],onStep:1,active:'home',loading:false,cache:{goals:[],tasks:[],journal:[],ideas:[],projects:[]}};welcome()}
function go(id){state.active=id;renderApp()}
db.auth.onAuthStateChange(async(_event,session)=>{state.session=session;state.user=session?.user||null;if(!session){if(!document.querySelector('.authShell'))welcome()}});
(async()=>{try{await loadSession();splash()}catch(e){console.error(e);app.innerHTML=`<div class="authPanel authFull"><div class="authBox">${msg('EA PLAN gagal memuat. Periksa koneksi dan konfigurasi Supabase.')}</div></div>`}})();
